<?xml version="1.0"?>
<package format="3">
  <name>rds_core</name>
  <version>0.1.0</version>
  <description>Core logic for the Reactive Driving Support (RDS) algorithm.</description>
  <maintainer email="your.email@domain.com">Your Name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rvo2_lib</depend>

  
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
